#!/bin/bash

BLUE=0xFF89B4FA
PINK=0xFFF5C2E7
RED=0xFFF38BA8
GREEN=0xFFA6E3A1

BACKGROUND=0xEB1E1E2E
TEXT=0xFFCFD6F1

# main bar & defaults
sketchybar --bar height=32 \
  y_offset=2 \
  padding_left=8 \
  padding_right=8 \
  color=0x00000000

sketchybar --default updates=when_shown \
  icon.font="JetBrainsMono Nerd Font:Regular:14" \
  icon.color=0xFFFFFFFF \
  label.font="JetBrainsMono Nerd Font:Regular:14" \
  background.color=0x00000000 \
  y_offset=0

# ~~ left items ~~

# space numbers
sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    icon="$sid" \
    icon.color=$TEXT \
    icon.highlight_color=$RED \
    icon.align=center \
    icon.width=30 \
    label.drawing=off \
    label="$sid" \
    click_script="aerospace workspace $sid" \
    script="./scripts/space.sh $sid"
done

# consolidate space numbers and add a background
sketchybar --add bracket spaces '/space\..*/' \
  --set spaces background.color=$BACKGROUND \
  background.corner_radius=15 \
  background.border_width=1 \
  background.border_color=$PINK \
  blur_radius=2 \
  background.height=30

# update defaults
sketchybar --default \
  background.color=$BACKGROUND \
  blur_radius=2 \
  background.corner_radius=15 \
  background.height=30 \
  icon.padding_left=12 \
  icon.padding_right=4 \
  label.padding_left=4 \
  label.padding_right=12 \
  label.color=$TEXT \
  background.padding_left=8 \
  background.border_width=1

# app title
sketchybar --add event title_change
sketchybar --add item title left \
  --set title label.padding_left=12 \
  label="Title" \
  label.color=$TEXT \
  background.padding_left=8 \
  icon.padding_left=0 \
  icon.padding_right=0 \
  script='./scripts/title.sh' \
  background.border_color=$PINK \
  update_freq=1 \
  label.max_chars=54
# scroll_texts=on \
# label.scroll_duration=200

sketchybar --subscribe title title_change

# ~~ right items ~~

# time
sketchybar --add item time right \
  --set time icon=󱑎 \
  icon.color=$BLUE \
  background.border_color=$BLUE \
  label="$(date '+%I:%M %p')" \
  script='./scripts/time.sh' \
  update_freq=1

# date
sketchybar --add item date right \
  --set date icon=󱨰 \
  icon.color=$GREEN \
  background.border_color=$GREEN \
  label="$(date '+%a %b %d')" \
  script='./scripts/date.sh' \
  update_freq=60 # every minute

# battery
sketchybar --add item battery right \
  --set battery icon= \
  icon.color=$RED \
  background.border_color=$RED \
  label="--%" \
  script='./scripts/battery.sh' \
  update_freq=60 # every minute

sketchybar --add item title_proxy right \
  --set title_proxy y_offset=100 \
  label="Title"

# finish config
sketchybar --hotload on
sketchybar --update
