#!/bin/bash

BLUE=0xFF89B4FA
RED=0xFFF38BA8
GREEN=0xFFA6E3A1
TEXT=0xFFCFD6F1

# main bar & defaults
sketchybar --bar height=30 \
  y_offset=4 \
  margin=10 \
  corner_radius=12 \
  border_width=0 \
  blur_radius=20 \
  color=0xcc1e1e2e \
  padding_left=12 \
  padding_right=12 \
  notch_width=188

sketchybar --default updates=when_shown \
  icon.font="JetBrainsMono Nerd Font:Regular:14" \
  icon.color=0xFFFFFFFF \
  label.font="JetBrainsMono Nerd Font:Regular:14" \
  background.color=0x00000000 \
  y_offset=0

# ~~ left items ~~

# space numbers
sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    icon="$sid" \
    icon.color=$TEXT \
    icon.highlight_color=$RED \
    icon.align=center \
    icon.width=30 \
    label.drawing=off \
    label="$sid" \
    click_script="aerospace workspace $sid" \
    script="./scripts/space.sh $sid"
done

# consolidate space numbers and add a background
sketchybar --add bracket spaces '/space\..*/' \
  --set spaces background.color=0x00000000 \
  background.border_width=0

# update defaults
sketchybar --default \
  background.color=0x00000000 \
  icon.padding_left=10 \
  icon.padding_right=10 \
  label.padding_left=4 \
  label.padding_right=10 \
  label.color=$TEXT \
  background.padding_left=4 \
  background.border_width=0

# app title
sketchybar --add event title_change
sketchybar --add item title left \
  --set title label.padding_left=12 \
  label="Title" \
  label.color=$TEXT \
  background.padding_left=8 \
  icon.padding_left=0 \
  icon.padding_right=0 \
  script='./scripts/title.sh' \
  update_freq=1 \
  label.max_chars=54

sketchybar --subscribe title title_change

# ~~ center items ~~

# time
sketchybar --add item time center \
  --set time icon=󱑎 \
  icon.color=$BLUE \
  label="$(date '+%I:%M %p')" \
  script='./scripts/time.sh' \
  update_freq=1

# weather
sketchybar --add item weather center \
  --set weather icon=󰖜 \
  icon.color=$GREEN \
  label="...°F" \
  script='./scripts/weather.sh' \
  update_freq=300

# ~~ right items ~~

# cpu
sketchybar --add item cpu right \
  --set cpu icon= \
  icon.color=$BLUE \
  label="--%" \
  script='./scripts/cpu.sh' \
  update_freq=2

# date
sketchybar --add item date right \
  --set date icon=󱨰 \
  icon.color=$GREEN \
  label="$(date '+%a %b %d')" \
  script='./scripts/date.sh' \
  update_freq=60 # every minute

# battery
sketchybar --add item battery right \
  --set battery icon= \
  icon.color=$RED \
  label="--%" \
  script='./scripts/battery.sh' \
  update_freq=60 # every minute

sketchybar --add item title_proxy right \
  --set title_proxy y_offset=100 \
  label="Title"

# finish config
sketchybar --hotload on
sketchybar --update
