{
  pkgs,
  myvars,
  ...
}: {
  imports = [
    ./base
    ../base.nix

    ./desktop
  ];

  ####################################################################
  #  NixOS's Configuration for Wayland based Window Manager
  ####################################################################
  xdg.portal = {
    enable = true;
    wlr.enable = true;
    extraPortals = with pkgs; [
      xdg-desktop-portal-wlr
    ];
  };

  services = {
    xserver.enable = false; # disable xorg server
    # https://wiki.archlinux.org/title/Greetd
    greetd = {
      enable = true;
      settings = {
        default_session = {
          user = myvars.username;
          # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
          # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
          command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
        };
      };
    };
  };

  # https://mynixos.com/home-manager/option/programs.hyprlock.enable
  security.pam.services.hyprlock = {};
}
